import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT = path.resolve(__dirname, '..');
const LIBHARU_DIR = path.join(ROOT, 'libharu');
const LIBPNG_DIR = path.join(ROOT, 'libpng');
const LIBHARU_VERSION = process.env.LIBHARU_VERSION || '2.4.6';
const LIBPNG_VERSION = process.env.LIBPNG_VERSION || '1.6.58';
const LIBHARU_TARBALL = `libharu-${LIBHARU_VERSION}.tar.gz`;
const LIBPNG_TARBALL = `libpng-${LIBPNG_VERSION}.tar.gz`;
const LIBHARU_URL = `https://github.com/libharu/libharu/releases/download/v${LIBHARU_VERSION}/${LIBHARU_TARBALL}`;
const LIBHARU_FALLBACK_URL = `https://github.com/libharu/libharu/archive/refs/tags/v${LIBHARU_VERSION}.tar.gz`;
const LIBPNG_URL = `https://github.com/pnggroup/libpng/releases/download/v${LIBPNG_VERSION}/${LIBPNG_TARBALL}`;
const LIBPNG_FALLBACK_URL = `https://download.sourceforge.net/libpng/${LIBPNG_TARBALL}`;

function log(message) {
  console.log(`[prepare-libharu] ${message}`);
}

function exists(file) {
  try {
    fs.accessSync(file);
    return true;
  } catch {
    return false;
  }
}

function writeConfigHeader() {
  const configPath = path.join(LIBHARU_DIR, 'include', 'hpdf_config.h');
  const configContent = `/* Generated by scripts/prepare-libharu.js for libharu ${LIBHARU_VERSION}. */
#ifndef _HPDF_CONFIG_H
#define _HPDF_CONFIG_H

#define LIBHPDF_HAVE_DLFCN_H 1
#define LIBHPDF_HAVE_INTTYPES_H 1
#define LIBHPDF_HAVE_ZLIB 1
#define LIBHPDF_HAVE_LIBPNG 1
#define LIBHPDF_HAVE_MEMORY_H 1
#define LIBHPDF_HAVE_STDINT_H 1
#define LIBHPDF_HAVE_STDLIB_H 1
#define LIBHPDF_HAVE_STRINGS_H 1
#define LIBHPDF_HAVE_STRING_H 1
#define LIBHPDF_HAVE_SYS_STAT_H 1
#define LIBHPDF_HAVE_SYS_TYPES_H 1
#define LIBHPDF_HAVE_UNISTD_H 1
#define LIBHPDF_STDC_HEADERS 1

#endif /* _HPDF_CONFIG_H */
`;
  fs.writeFileSync(configPath, configContent, 'utf8');
  log(`Wrote ${configPath}`);
}

function downloadFile(url, dest) {
  const curl = 'curl -L --fail --max-time 120';
  try {
    execSync(`${curl} -o "${dest}" "${url}"`, { stdio: 'inherit' });
    return;
  } catch {
    // ignore, try wget
  }
  try {
    execSync(`wget --timeout=120 -O "${dest}" "${url}"`, { stdio: 'inherit' });
  } catch (error) {
    throw new Error(`Failed to download ${url}: ${error.message}`);
  }
}

function ensureLibharu() {
  if (exists(LIBHARU_DIR) &&
      exists(path.join(LIBHARU_DIR, 'include', 'hpdf.h')) &&
      exists(path.join(LIBHARU_DIR, 'include', 'hpdf_config.h'))) {
    log('libharu already prepared.');
    return;
  }

  if (exists(LIBHARU_DIR) && exists(path.join(LIBHARU_DIR, 'include', 'hpdf.h')) &&
      !exists(path.join(LIBHARU_DIR, 'include', 'hpdf_config.h'))) {
    log('libharu sources present, generating missing config header...');
    return;
  }

  if (exists(LIBHARU_DIR)) {
    log('Removing incomplete libharu directory...');
    fs.rmSync(LIBHARU_DIR, { recursive: true, force: true });
  }

  const tempDir = fs.mkdtempSync(path.join(ROOT, 'libharu-download-'));
  const tarballPath = path.join(tempDir, LIBHARU_TARBALL);

  try {
    log(`Downloading libharu v${LIBHARU_VERSION}...`);
    try {
      downloadFile(LIBHARU_URL, tarballPath);
    } catch {
      log('Primary download failed, trying fallback URL...');
      downloadFile(LIBHARU_FALLBACK_URL, tarballPath);
    }

    log('Extracting libharu...');
    execSync(`tar -xzf "${tarballPath}" -C "${tempDir}"`, { stdio: 'inherit' });

    const extractedDirs = fs.readdirSync(tempDir)
      .filter((name) => name.startsWith('libharu') && fs.statSync(path.join(tempDir, name)).isDirectory());
    if (extractedDirs.length !== 1) {
      throw new Error(`Expected exactly one extracted libharu directory, found: ${extractedDirs.join(', ')}`);
    }

    fs.renameSync(path.join(tempDir, extractedDirs[0]), LIBHARU_DIR);
    writeConfigHeader();
    log('libharu prepared successfully.');
  } finally {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
}

function ensureLibpng() {
  if (exists(LIBPNG_DIR) &&
      exists(path.join(LIBPNG_DIR, 'png.h')) &&
      exists(path.join(LIBPNG_DIR, 'pnglibconf.h'))) {
    log('libpng already prepared.');
    return;
  }

  if (exists(LIBPNG_DIR)) {
    log('Removing incomplete libpng directory...');
    fs.rmSync(LIBPNG_DIR, { recursive: true, force: true });
  }

  const tempDir = fs.mkdtempSync(path.join(ROOT, 'libpng-download-'));
  const tarballPath = path.join(tempDir, LIBPNG_TARBALL);

  try {
    log(`Downloading libpng v${LIBPNG_VERSION}...`);
    try {
      downloadFile(LIBPNG_URL, tarballPath);
    } catch {
      log('Primary download failed, trying fallback URL...');
      downloadFile(LIBPNG_FALLBACK_URL, tarballPath);
    }

    log('Extracting libpng...');
    execSync(`tar -xzf "${tarballPath}" -C "${tempDir}"`, { stdio: 'inherit' });

    const extractedDirs = fs.readdirSync(tempDir)
      .filter((name) => name.startsWith('libpng') && fs.statSync(path.join(tempDir, name)).isDirectory());
    if (extractedDirs.length !== 1) {
      throw new Error(`Expected exactly one extracted libpng directory, found: ${extractedDirs.join(', ')}`);
    }

    fs.renameSync(path.join(tempDir, extractedDirs[0]), LIBPNG_DIR);

    // libpng needs a generated pnglibconf.h. Copy the prebuilt template.
    const libpngconf = path.join(LIBPNG_DIR, 'scripts', 'pnglibconf.h.prebuilt');
    const dest = path.join(LIBPNG_DIR, 'pnglibconf.h');
    if (exists(libpngconf) && !exists(dest)) {
      fs.copyFileSync(libpngconf, dest);
      log(`Copied ${dest}`);
    }

    log('libpng prepared successfully.');
  } finally {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
}


ensureLibharu();
ensureLibpng();
writeConfigHeader();
